# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d63d034e1f35adac32ec5645ee1e2bfb47838ca6baba350cddf85f133667b919c1bd6730505a262748308d21999fbfff11eceb4eeb4d4a17069b0537786b380

test:
  secret_key_base: 5a643c0d04d19a521d983eef7e1e4efddb102ae4bf745c3c964e941b363356d6b8dcd8968f0db2ba1847ec79cbb17af3b822868119f7bfc3bd5f71674280f878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
